### ISSUE TITLE
请问下，你跑这个模型得到的结果是多少呢。

### ISSUE THREAD

**Issue by zz10001** [Westrel/lits2017#1]
弱弱再问下跑了几个epoch

**Comment by Westrel** [comment]
1000epoch，上下10张slice的时候dice系数0.76，jaccard系数0.63，后来5000epoch，上下20张效果明显变好，但是我没记，大概两个值都接近0.9
第一次跑的时候把肺都标记出来了，第二次的时候从输出结果来看还是怪不错的

**Comment by zz10001** [comment]
十分感谢回复！追问一下，你使用了多少个数据ji那些测试的啊。

**Comment by Westrel** [comment]
lits数据集总共一百来张nii图像，然后我训练用的是90张左右，测试集是7张新的加3张训练集的数据
